### ISSUE TITLE
Usage examples

### ISSUE THREAD

**Issue by bararchy** [Groogy/boleite#1]
How about adding some small and simple usage examples that can show people how to test,QA and help develop this shard ? :)

**Comment by Groogy** [comment]
Will do when the project is more at a minimal viable product kind of stage. Right now too much needs to be added before it's worth adding those kind of things. For now using https://github.com/Groogy/ego as an example until I reach that stage.

**Comment by Demonstrandum** [comment]
Are we there yet?

**Comment by Groogy** [comment]
Yeah now the framework can very much be used so a usage example is in order. Though I'm still not going to claim that it's finished so various part might have breaking changes at any point.

I'll get to do some usage examples to get an application started at the very least.

**Comment by Groogy** [comment]
I've added a usage example now on the read me, it's quite hefty so should probably put work into making "basic startup" stuff simpler so it doesn't look as intimidating.

Also took this commit as the first version of Boleite.
